import requests
translation = {
    "activatables": "АКТИВИРУЕМЫЕ ТРОФЕИ",
    "ark_f": "СОБРАНО САМОК (КОВЧЕГ)",
    "ark_m": "СОБРАНО САМЦОВ (КОВЧЕГ)",
    "arena_won": "ПОБЕД НА АРЕНЕ",
    "arena_lost": "ПОРАЖЕНИЙ НА АРЕНЕ",
    "arena_fight": "В БОЮ/НА АРЕНЕ",
    "ark_completed_at": "КОВЧЕГ ПОСТРОЕН",
    "ark_name": "НАЗВАНИЕ КОВЧЕГА",
    "alignment": "ХАРАКТЕР",
    "aura": "АУРА",
    "pairs_at": "СБОР ТВАРЕЙ ЗАВЕРШЁН",
    "book_at": "КНИГА НАПИСАНА",
    "souls_at": "СБОР ДУШ ЗАВЕРШЁН",
    "boss_name": "ИМЯ БОССА",
    "boss_power": "МОЩЬ БОССА",
    "bricks_cnt": "КИРПИЧИ",
    "clan": "ГИЛЬДИЯ",
    "clan_position": "ЗВАНИЕ В ГИЛЬДИИ",
    "diary_last": "ДНЕВНИК",
    "eye_last": "ТРЕТИЙ ГЛАЗ",
    "distance": "РАССТОЯНИЕ ДО СТОЛИЦЫ",
    "exp_progress": "ПРОГРЕСС ОПЫТА",
    "expired": "ДАННЫЕ НЕАКТУАЛЬНЫ",
    "fight_type": "ТИП БОЯ",
    "godpower": "ПРАНА",
    "gold_approx": "ЗОЛОТО",
    "gender": "ПОЛ",
    "godname": "ИМЯ БОГА",
    "health": "ЗДОРОВЬЕ",
    "inventory_max_num": "МАКС. ИНВЕНТАРЬ",
    "inventory_num": "ЗАНЯТО МЕСТ",
    "level": "УРОВЕНЬ",
    "max_health": "МАКС. ЗДОРОВЬЕ",
    "motto": "ДЕВИЗ",
    "name": "ИМЯ ГЕРОЯ",
    "pet": "ПИТОМЕЦ",
    "quest_progress": "ПРОГРЕСС КВЕСТА",
    "quest": "КВЕСТ",
    "side_job_progress": "ПРОГРЕСС ПОДРЯДА",
    "side_job": "ПОДРЯД",
    "savings": "СБЕРЕЖЕНИЯ",
    "savings_completed_at": "СБОР ПЕНСИИ ЗАВЕРШЁН",
    "shop_name": "НАЗВАНИЕ ЛАВКИ",
    "souls_percent": "СОБРАНО ДУШ (%)",
    "relics_percent": "НАЙДЕНО РЕЛИКВИЙ (%)",
    "t_level": "УРОВЕНЬ ТОРГОВЦА",
    "temple_completed_at": "ХРАМ ПОСТРОЕН",
    "town_name": "ГОРОД",
    "wood_cnt": "ПОЛЕНЬЯ",
    "words": "СОБРАНО СЛОВ"
}
data = requests.get(f"https://godville.net/gods/api/{open('api.txt').read().strip()}").json()
for k, v in data.items():
    if v not in [None, "", [], {}]:
        ru_name = translation.get(k, k.upper())
        print(f"{ru_name}: {v}")